In [3]:
import pandas as pd
import re

df_jobs = pd.read_csv("../data/raw/job_descriptions.csv")

print("Dataset Shape:", df_jobs.shape)
df_jobs.head()

Dataset Shape: (10, 6)

,job_id,company,role,location,experience_level,description
0,1,TechCorp,Data Analyst,Bangalore,Entry Level,We are looking for a Data Analyst with strong ...
1,2,DataWorks,Data Analyst,Hyderabad,Entry Level,"Candidate should have knowledge of SQL, Python..."
2,3,AnalyticsPro,Data Scientist,Bangalore,Entry Level,"Strong Python, machine learning, statistics, S..."
3,4,FinTech Solutions,Business Analyst,Pune,Entry Level,"Strong communication, Excel, SQL, Power BI, pr..."
4,5,CloudTech,Software Developer,Noida,Entry Level,"Candidate should have strong programming, Java..."

In [2]:
import pandas as pd
import re

df_jobs = pd.read_csv("../data/raw/job_descriptions.csv")

print("Dataset Shape:", df_jobs.shape)
df_jobs.head()

Dataset Shape: (10, 6)

,job_id,company,role,location,experience_level,description
0,1,TechCorp,Data Analyst,Bangalore,Entry Level,We are looking for a Data Analyst with strong ...
1,2,DataWorks,Data Analyst,Hyderabad,Entry Level,"Candidate should have knowledge of SQL, Python..."
2,3,AnalyticsPro,Data Scientist,Bangalore,Entry Level,"Strong Python, machine learning, statistics, S..."
3,4,FinTech Solutions,Business Analyst,Pune,Entry Level,"Strong communication, Excel, SQL, Power BI, pr..."
4,5,CloudTech,Software Developer,Noida,Entry Level,"Candidate should have strong programming, Java..."

In [4]:
skill_dictionary = [
    "Python",
    "SQL",
    "Excel",
    "Power BI",
    "Tableau",
    "Statistics",
    "Machine Learning",
    "Deep Learning",
    "Data Visualization",
    "DAX",
    "Java",
    "Programming",
    "Data Structures",
    "Algorithms",
    "Communication",
    "Presentation",
    "Business Analysis",
    "Problem Solving"
]

In [5]:
def extract_skills(text):
    text = text.lower()
    
    found_skills = []
    
    for skill in skill_dictionary:
        if skill.lower() in text:
            found_skills.append(skill)
    
    return found_skills


df_jobs["extracted_skills"] = df_jobs["description"].apply(extract_skills)

df_jobs[["role", "company", "extracted_skills"]]

,role,company,extracted_skills
0,Data Analyst,TechCorp,"[Python, SQL, Excel, Power BI, Statistics, Dat..."
1,Data Analyst,DataWorks,"[Python, SQL, Excel, Power BI, Tableau]"
2,Data Scientist,AnalyticsPro,"[Python, SQL, Statistics, Machine Learning, De..."
3,Business Analyst,FinTech Solutions,"[SQL, Excel, Power BI, Communication, Presenta..."
4,Software Developer,CloudTech,"[Python, Java, Programming, Data Structures, A..."
5,ML Engineer,AI Labs,"[Python, SQL, Statistics, Machine Learning, De..."
6,BI Analyst,Insight Analytics,"[SQL, Excel, Power BI, Data Visualization, DAX]"
7,Data Analyst,Global Systems,"[Python, SQL, Excel, Power BI, Statistics, Com..."
8,Data Scientist,TechNova,"[Python, SQL, Statistics, Machine Learning, De..."
9,Business Analyst,BusinessHub,"[SQL, Excel, Power BI, Communication, Presenta..."

In [6]:
from collections import Counter

skill_counter = Counter()

for skills in df_jobs["extracted_skills"]:
    skill_counter.update(skills)

market_demand = pd.DataFrame(
    skill_counter.items(),
    columns=["Skill", "Job_Count"]
)

market_demand["Demand_Percentage"] = (
    market_demand["Job_Count"] / len(df_jobs) * 100
)

market_demand = market_demand.sort_values(
    "Job_Count",
    ascending=False
).reset_index(drop=True)

display(market_demand)

                 Skill  Job_Count  Demand_Percentage
0                  SQL          9               90.0
1               Python          7               70.0
2                Excel          6               60.0
3             Power BI          6               60.0
4           Statistics          5               50.0
5   Data Visualization          4               40.0
6     Machine Learning          3               30.0
7        Deep Learning          3               30.0
8        Communication          3               30.0
9         Presentation          2               20.0
10         Programming          2               20.0
11             Tableau          1               10.0
12   Business Analysis          1               10.0
13                Java          1               10.0
14     Data Structures          1               10.0
15          Algorithms          1               10.0
16     Problem Solving          1               10.0
17                 DAX          1               10.0

In [7]:
market_demand.to_csv(
    "../reports/market_skill_demand.csv",
    index=False
)

df_jobs.to_csv(
    "../data/processed/job_skill_analysis.csv",
    index=False
)

print("Job description analysis completed!")

Job description analysis completed!

In [8]:
import pandas as pd

students = pd.read_csv("../data/processed/modeling_dataset.csv")
market_demand = pd.read_csv("../reports/market_skill_demand.csv")

print("Students:", students.shape)
print("Market Skills:", market_demand.shape)

display(market_demand)

Students: (10000, 45)
Market Skills: (18, 3)

                 Skill  Job_Count  Demand_Percentage
0                  SQL          9               90.0
1               Python          7               70.0
2                Excel          6               60.0
3             Power BI          6               60.0
4           Statistics          5               50.0
5   Data Visualization          4               40.0
6     Machine Learning          3               30.0
7        Deep Learning          3               30.0
8        Communication          3               30.0
9         Presentation          2               20.0
10         Programming          2               20.0
11             Tableau          1               10.0
12   Business Analysis          1               10.0
13                Java          1               10.0
14     Data Structures          1               10.0
15          Algorithms          1               10.0
16     Problem Solving          1               10.0
17                 DAX          1               10.0

In [9]:
skill_columns = {
    "Python": "python_score",
    "SQL": "sql_score",
    "Excel": "excel_score",
    "Power BI": "powerbi_score",
    "Statistics": "statistics_score",
    "Machine Learning": "ml_score",
    "Data Visualization": "data_visualization_score",
    "Java": "java_score",
    "Communication": "communication_score",
    "Presentation": "presentation_score",
    "Programming": "coding_score",
    "Problem Solving": "logical_reasoning_score"
}

In [10]:
def calculate_market_skill_gap(student):

    results = []

    for skill, column in skill_columns.items():

        student_score = student[column]

        market_row = market_demand[
            market_demand["Skill"] == skill
        ]

        if not market_row.empty:
            demand = market_row.iloc[0]["Demand_Percentage"]
        else:
            demand = 0

        gap = max(0, 100 - student_score)

        priority = gap * (demand / 100)

        results.append({
            "Skill": skill,
            "Student_Score": round(student_score, 2),
            "Market_Demand": round(demand, 2),
            "Skill_Gap": round(gap, 2),
            "Priority": round(priority, 2)
        })

    return pd.DataFrame(results)

In [11]:
student = students.iloc[0]

market_gap = calculate_market_skill_gap(student)

market_gap = market_gap.sort_values(
    "Priority",
    ascending=False
).reset_index(drop=True)

display(market_gap)

                 Skill  Student_Score  Market_Demand  Skill_Gap  Priority
0             Power BI          23.07           60.0      76.93     46.16
1                Excel          39.85           60.0      60.15     36.09
2               Python          63.07           70.0      36.93     25.85
3   Data Visualization          52.34           40.0      47.66     19.06
4     Machine Learning          42.17           30.0      57.83     17.35
5           Statistics          68.04           50.0      31.96     15.98
6        Communication          64.57           30.0      35.43     10.63
7          Programming          54.88           20.0      45.12      9.02
8      Problem Solving          41.50           10.0      58.50      5.85
9                 Java          50.49           10.0      49.51      4.95
10        Presentation          85.22           20.0      14.78      2.96
11                 SQL          97.70           90.0       2.30      2.07

In [12]:
top_skill_gaps = market_gap.head(5)

print("Top Skills to Improve:")
display(top_skill_gaps)

Top Skills to Improve:

                Skill  Student_Score  Market_Demand  Skill_Gap  Priority
0            Power BI          23.07           60.0      76.93     46.16
1               Excel          39.85           60.0      60.15     36.09
2              Python          63.07           70.0      36.93     25.85
3  Data Visualization          52.34           40.0      47.66     19.06
4    Machine Learning          42.17           30.0      57.83     17.35

In [13]:
market_gap.to_csv(
    "../reports/student_market_skill_gap.csv",
    index=False
)

print("Student market skill gap analysis completed!")

Student market skill gap analysis completed!